export type {
  ArtifactReference,
  DiagramDocument as Diagram,
  DiagramEdgeMetadata,
  DiagramLinkReference,
  DiagramNodeMetadata,
  DiagramPerspective,
  DiagramPerspectiveKind,
  DiagramSummary as DiagramMeta,
  KnowledgePattern,
  ProjectColumn,
  ProjectDocument,
  ProjectEpic,
  ProjectSummary,
  ProjectTask,
  ProjectTaskDependency,
  ProjectTaskLink,
  ProjectTaskMetadata,
  ProjectTaskPriority,
  TroubleshootingSession,
} from "../../shared/planview/domain.js";
